name: do-the-job
on: push
jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      -
        run: |
          tree ${HOME}

  #create-matrix:
  #  runs-on: ubuntu-latest
  #  outputs:
  #    matrix: ${{ steps.set-includes.outputs.matrix }}
  #  steps:
  #  - id: set-includes
  #    run: echo "::set-output name=matrix::{\"runtime\":[\"a\",\"b\"],\"include\":[{\"runtime\":\"a\",\"needs\":\"start-runner-a\",\"runs-on\":\"needs.start-runner-a.outputs.runner-label\"},{\"runtime\":\"b\",\"needs\":\"start-runner-b\",\"runs-on\":\"needs.start-runner-b.outputs.runner-label\"}]}"


  #run-job-a:
  #  needs: start-runner-a
  #  runs-on: ${{ needs.start-runner-a.outputs.runner-label }}
  #  steps:
  #    -
  #      run: echo 'hello from job a'

  #run-job-b:
  #  needs: start-runner-b
  #  runs-on: ${{ needs.start-runner-b.outputs.runner-label }}
  #  steps:
  #    -
  #      run: echo 'hello from job b'

  #run-job:
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      runtime:
  #        - a
  #        - b
  #  needs: start-runner-${{ matrix.runtime }}
  #  runs-on: needs.start-runner-${{ matrix.runtime }}.outputs.runner-label
  #  steps:
  #    -
  #      run: echo 'hello from job ${{ matrix.runtime }}'
#
  #start-runner-a:
  #  runs-on: ubuntu-latest
  #  outputs:
  #    runner-label: ${{ steps.start-runner.outputs.runner-label }}
  #    aws-region: ${{ steps.start-runner.outputs.aws-region }}
  #    aws-instance-id: ${{ steps.start-runner.outputs.aws-instance-id }}
  #  steps:
  #    -
  #      id: start-runner
  #      uses: audacious-network/aws-github-runner@v1.0.17
  #      with:
  #        mode: start
  #        github-token: ${{ secrets.GH_SHR_TOKEN }}
  #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        aws-region: us-east-1
  #        aws-instance-type: t3.nano
  #        aws-instance-lifecycle: spot
  #        aws-image-search-pattern: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
  #        aws-image-search-owners: '["099720109477"]' # canonical
#
  #stop-runner-a:
  #  needs:
  #    - start-runner-a
  #    - run-job
  #  runs-on: ubuntu-latest
  #  if: ${{ always() }}
  #  steps:
  #    -
  #      uses: audacious-network/aws-github-runner@v1.0.17
  #      with:
  #        mode: stop
  #        github-token: ${{ secrets.GH_SHR_TOKEN }}
  #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        aws-region: ${{ needs.start-runner-a.outputs.aws-region }}
  #        runner-label: ${{ needs.start-runner-a.outputs.runner-label }}
  #        aws-instance-id: ${{ needs.start-runner-a.outputs.aws-instance-id }}
#
  #start-runner-b:
  #  runs-on: ubuntu-latest
  #  outputs:
  #    runner-label: ${{ steps.start-runner.outputs.runner-label }}
  #    aws-region: ${{ steps.start-runner.outputs.aws-region }}
  #    aws-instance-id: ${{ steps.start-runner.outputs.aws-instance-id }}
  #  steps:
  #    -
  #      id: start-runner
  #      uses: audacious-network/aws-github-runner@v1.0.17
  #      with:
  #        mode: start
  #        github-token: ${{ secrets.GH_SHR_TOKEN }}
  #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        aws-region: us-east-1
  #        aws-instance-type: t3.nano
  #        aws-instance-lifecycle: spot
  #        aws-image-search-pattern: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
  #        aws-image-search-owners: '["099720109477"]' # canonical
#
  #stop-runner-b:
  #  needs:
  #    - start-runner-b
  #    - run-job
  #  runs-on: ubuntu-latest
  #  if: ${{ always() }}
  #  steps:
  #    -
  #      uses: audacious-network/aws-github-runner@v1.0.17
  #      with:
  #        mode: stop
  #        github-token: ${{ secrets.GH_SHR_TOKEN }}
  #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        aws-region: ${{ needs.start-runner-b.outputs.aws-region }}
  #        runner-label: ${{ needs.start-runner-b.outputs.runner-label }}
  #        aws-instance-id: ${{ needs.start-runner-b.outputs.aws-instance-id }}
#