name: do-the-job
on: push
jobs:
  start-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.start-runner.outputs.runner-label }}
      aws-region: ${{ steps.start-runner.outputs.aws-region }}
      aws-instance-id: ${{ steps.start-runner.outputs.aws-instance-id }}
    steps:
      -
        id: start-runner
        uses: audacious-network/aws-github-runner@v1.0.17
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-instance-type: t3.nano
          aws-instance-lifecycle: spot
          aws-image-search-pattern: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
          aws-image-search-owners: '["099720109477"]' # canonical
  do-the-job:
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.runner-label }}
    steps:
      -
        run: echo 'hello world!'
  stop-runner:
    needs:
      - start-runner
      - do-the-job
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      -
        uses: audacious-network/aws-github-runner@v1.0.17
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ needs.start-runner.outputs.aws-region }}
          runner-label: ${{ needs.start-runner.outputs.runner-label }}
          aws-instance-id: ${{ needs.start-runner.outputs.aws-instance-id }}
